package pl.put.poznan;

import pl.put.poznan.Main.Question
import pl.put.poznan.Main.Answer
import java.util.Scanner
import java.util.Arrays

function String askQuestion(Question q) {
        System.out.println(q.content);
        for(String posan : q.possibleAnswers) System.out.println("-" + posan);
        Scanner s = new Scanner(System.in);
        String ans;
        do {
            System.out.println("Type one of the answers listed above:");
            ans = s.nextLine();
           //if(ans.equals("q")) drools.halt();
        } while(!Arrays.asList(q.possibleAnswers).contains(ans) && !ans.equals("q"));
        return ans;
}

function printResult(String typeface) {
    System.out.println("Perfect typeface for you is " + typeface + ".");
}

//rule "ask question"
//    when
//        $q : Question($subj : subject)
//        not Font()
//    String ans = askQuestion($q);
//end

rule "ask about kind of project"
    salience 50
    when
        $q : Question($subj : subject == "kind of project")
        not Answer(subject == $subj)
    then
        String ans = askQuestion($q);
//        kcontext.getKieRuntime().getAgenda().getAgendaGroup(ans).setFocus();
        insert(new Answer($subj, ans));
end

rule "ask if user is in doubt"
//    agenda-group "book"
    salience 49
    when
        $q : Question($subj : subject == "in doubt")
        not Answer(subject == $subj)
        Answer(subject == "kind of project", answer == "book")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if champion in usability needed"
//    agenda-group "book"
    salience 48
    when
        $q : Question($subj : subject == "champion in usability")
        not Answer(subject == $subj)
        Answer(subject == "in doubt", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user loves Garamond"
//    agenda-group "book"
    salience 47
    when
        $q : Question($subj : subject == "loves Garamond")
        not Answer(subject == $subj)
        Answer(subject == "champion in usability", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user would would want a larger eye"
//    agenda-group "book"
    salience 46
    when
        $q : Question($subj : subject == "would want a larger eye")
        not Answer(subject == $subj)
        Answer(subject == "loves Garamond", answer == "yes")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user wants as Sans Serif"
//    agenda-group "book"
    salience 45
    when
        $q : Question($subj : subject == "wants sans serif")
        not Answer(subject == $subj)
        Answer(subject == "loves Garamond", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask about user opinion of Eric Gill"
//    agenda-group "book"
    salience 44
    when
        $q : Question($subj : subject == "opinion of Eric Gill")
        not Answer(subject == $subj)
        Answer(subject == "wants sans serif", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user likes humanistic forms"
//    agenda-group "book"
    salience 43
    when
        $q : Question($subj : subject == "likes humanistic forms")
        not Answer(subject == $subj)
        Answer(subject == "opinion of Eric Gill", answer == "bad")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask what cheese user preferes"
//    agenda-group "book"
    salience 42
    when
        $q : Question($subj : subject == "preferred cheese")
        not Answer(subject == $subj)
        Answer(subject == "likes humanistic forms", answer == "yes")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user likes something condensed"
//    agenda-group "infographic"
    salience 49
    when
        $q : Question($subj : subject == "likes condensed")
        not Answer(subject == $subj)
        Answer(subject == "kind of project", answer == "infographic")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user got a lot of tables"
//    agenda-group "infographic"
    salience 48
    when
        $q : Question($subj : subject == "got a lot of tables")
        not Answer(subject == $subj)
        Answer(subject == "likes condensed", answer == "yes")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user cried watching Terminator"
//    agenda-group "infographic"
    salience 47
    when
        $q : Question($subj : subject == "cried watching Terminator")
        not Answer(subject == $subj)
        Answer(subject == "got a lot of tables", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask where user is going to use typerface"
//    agenda-group "newspaper"
    salience 49
    when
        $q : Question($subj : subject == "where in newspaper")
        not Answer(subject == $subj)
        Answer(subject == "kind of project", answer == "newspaper")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user is called boring"
//    agenda-group "newspaper"
    salience 48
    when
        $q : Question($subj : subject == "is called boring")
        not Answer(subject == $subj)
        Answer(subject == "where in newspaper", answer == "text face")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user wants something heavily used"
//    agenda-group "newspaper"
    salience 47
    when
        $q : Question($subj : subject == "heavily used")
        not Answer(subject == $subj)
        Answer(subject == "is called boring", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user wants something award winning"
//    agenda-group "newspaper"
    salience 46
    when
        $q : Question($subj : subject == "award winning")
        not Answer(subject == $subj)
        Answer(subject == "heavily used", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if Mr. Spiekermann is mostly right"
    agenda-group "newspaper"
    salience 48
    when
        $q : Question($subj : subject == "thinks Spiekermann is right")
        not Answer(subject == $subj)
        Answer(subject == "where in newspaper", answer == "combination")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if Netherlands is nice"
    agenda-group "newspaper"
    salience 47
    when
        $q : Question($subj : subject == "Netherlands is nice")
        not Answer(subject == $subj)
        Answer(subject == "thinks Spierkermann is right", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user likes it traditional"
    agenda-group "newspaper"
    salience 48
    when
        $q : Question($subj : subject == "likes it traditional")
        not Answer(subject == $subj)
        Answer(subject == "where in newspaper", answer == "display")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if swiss is okay"
//    agenda-group "newspaper"
    salience 47
    when
        $q : Question($subj : subject == "ok with swiss")
        not Answer(subject == $subj)
        Answer(subject == "likes traditional", answer == "yes")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask about preferred age"
//    agenda-group "newpaper"
    salience 46
    when
        $q : Question($subj : subject == "preferred age")
        not Answer(subject == $subj)
        Answer(subject == "ok with swiss", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user wants something modern, yet planspoken"
//    agenda-group "newspaper"
    salience 47
    when
        $q : Question($subj : subject == "moder yet plainspoken")
        not Answer(subject == $subj)
        Answer(subject == "likes it traditional", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "ask if user pretends to live in nineties"
//    agenda-group "newspaper"
    salience 46
    when
        $q : Question($subj : subject == "pretend to live in nineties")
        not Answer(subject == $subj)
        Answer(subject == "modern yet plainspoken", answer == "no")
    then
        String ans = askQuestion($q);
        insert(new Answer($subj, ans));
end

rule "when to choose Syntax"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "no")
//       Answer(subject == "sans serif", answer == "no")
//       Answer(subject == "opinion of Eric Gill", answer == "bad")
//       Answer(subject == "likes humanistic forms", answer == "yes")
       Answer(subject == "preferred cheese", answer == "emmental")
    then
       printResult("Syntax");
end

rule "when to choose FF Scala"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "no")
//       Answer(subject == "sans serif", answer == "no")
//       Answer(subject == "opinion of Eric Gill", answer == "bad")
//       Answer(subject == "likes humanistic forms", answer == "yes")
       Answer(subject == "preferred cheese", answer == "gouda")
    then
       printResult("FF Scala");
end

rule "when to choose Baskerville"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "no")
//       Answer(subject == "sans serif", answer == "no")
//       Answer(subject == "opinion of Eric Gill", answer == "bad")
       Answer(subject == "likes humanistic forms", answer == "no")
    then
       printResult("Baskerville");
end

rule "when to choose Joanna"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "no")
//       Answer(subject == "sans serif", answer == "no")
       Answer(subject == "opinion of Eric Gill", answer == "good")
    then
       printResult("Joanna");
end

rule "when to choose Optima"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "yes")
       Answer(subject == "would want a larger eye", answer == "yes")
    then
       printResult("Optima");
end

rule "when to choose Sabon"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "yes")
       Answer(subject == "would want a larger eye", answer == "yes")
    then
       printResult("Sabon");
end

rule "when to choose Garamond"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "yes")
       Answer(subject == "would want a larger eye", answer == "yes")
    then
       printResult("Garamond");
end

rule "when to choose Minion"
    when
//       Answer(subject == "in doubt", answer == "no")
       Answer(subject == "champion in usablity", answer == "yes")
    then
       printResult("Minion");
end

rule "when to choose Caslon"
    when
       Answer(subject == "in doubt", answer == "yes")
    then
       printResult("Caslon");
end

rule "when to choose FF DIN"
    when
//       Answer(subject == "likes condensed", answer == "no")
//       Answer(subject == "got a lot of tables", answer == "no")
       Answer(subject == "cried watching Terminator", answer == "no")
    then
       printResult("FF DIN");
end

rule "when to choose OCR"
    when
//       Answer(subject == "likes condensed", answer == "no")
//       Answer(subject == "got a lot of tables", answer == "no")
       Answer(subject == "cried watching Terminator", answer == "yes")
    then
       printResult("OCR");
end

rule "when to choose Letter Gothic"
    when
//       Answer(subject == "likes condensed", answer == "no")
       Answer(subject == "got a lot of tables", answer == "yes")
    then
       printResult("Letter Gothic");
end

rule "when to choose Univers"
    when
       Answer(subject == "likes condensed", answer == "yes")
    then
       printResult("Univers");
end

rule "when to choose Proforma"
    when
//       Answer(subject == "where in newspaper", answer == "text face")
//       Answer(subject == "user is called boring", answer == "no")
//       Answer(subject == "heavily used", answer == "no")
       Answer(subject == "award winning", answer == "good")
    then
       printResult("Proforma");
end

rule "when to choose Miller"
    when
//       Answer(subject == "where in newspaper", answer == "text face")
//       Answer(subject == "user is called boring", answer == "no")
       Answer(subject == "heavily used", answer == "yes")
    then
       printResult("Miller");
end

rule "when to choose Times"
    when
//       Answer(subject == "where in newspaper", answer == "text face")
       Answer(subject == "user is called boring", answer == "yes")
    then
       printResult("Times");
end

rule "when to choose Swift"
    when
       Answer(subject == "where in newspaper", answer == "combination")
       Answer(subject == "thinks Spiekermann is right", answer == "no")
       Answer(subject == "Netherlands is nice", answer == "yes")
    then
       printResult("Swift");
end

rule "when to choose Arnhem"
    when
    (and
//       Answer(subject == "where in newspaper", answer == "text face")
//       Answer(subject == "user is called boring", answer == "no")
//       Answer(subject == "heavily used", answer == "no")
       Answer(subject == "award winning", answer == "bad")
    )
    or
    (and
//       Answer(subject == "where in newspaper", answer == "combination")
       Answer(subject == "thinks Spiekermann is right", answer == "yes")
    )
    then
       printResult("Arnhem");
end

rule "when to choose Interstate"
    when
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "yes")
//       Answer(subject == "ok with swiss", answer == "no")
       Answer(subject == "prefered age", answer == "new")
    then
       printResult("Interstate");
end

rule "when to choose Helvetica"
    when
   (and
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "yes")
       Answer(subject == "ok with swiss", answer == "yes")
   )
    or
   (and
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "no")
//       Answer(subject == "modern yet plainspoken", answer == "no")
       Answer(subject == "pretend to live in the nineties", answer == "yes")
   )
    then
       printResult("Helvetica");
end

rule "when to choose FF Meta"
    when
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "no")
//       Answer(subject == "modern yet plainspoken", answer == "no")
       Answer(subject == "pretend to live in the nineties", answer == "no")
    then
       printResult("FF Meta");
end

rule "when to choose Gotham"
    when
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "no")
       Answer(subject == "modern yet plainspoken", answer == "yes")
    then
       printResult("Gotham");
end
