package pl.put.poznan;

import pl.put.poznan.Main.Question
import pl.put.poznan.Main.Answer
import java.util.Scanner
import java.util.Arrays

function String askQuestion(Question q) {
        System.out.println(q.content);
        for(String posan : q.possibleAnswers) System.out.println("-" + posan);
        Scanner s = new Scanner(System.in);
        String ans;
        do {
            System.out.println("Type one of the answers listed above:");
            ans = s.nextLine();
           //if(ans.equals("q")) drools.halt();
        } while(!Arrays.asList(q.possibleAnswers).contains(ans) && !ans.equals("q"));
        return ans;
}

declare Font
    name: String
end

//rule "ask question"
//    when
//        $q : Question($subj : subject)
//        not Answer(subject == $subj)
//        not Font()
//    then
//    String ans = askQuestion($q);
//end

rule "ask about kind of project"
    salience 50
    when
        $q : Question($subj : subject == "kind of project")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        kcontext.getKieRuntime().getAgenda().getAgendaGroup(ans).setFocus();
        insert(new Answer($q.subject, ans));
end

rule "ask if user is in doubt"
    agenda-group "book"
    salience 49
    when
        $q : Question($subj : subject == "in doubt")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if champion in usability needed"
    agenda-group "book"
    salience 48
    when
        $q : Question($subj : subject == "champion in usability")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user loves Garamond"
    agenda-group "book"
    salience 47
    when
        $q : Question($subj : subject == "loves Garamond")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user would would want a larger eye"
    agenda-group "book"
    salience 46
    when
        $q : Question($subj : subject == "would want a larger eye")
        not Answer(subject == $subj)
        Answer(subject == "loves Garamond", answer == "yes")
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user wants as Sans Serif"
    agenda-group "book"
    salience 45
    when
        $q : Question($subj : subject == "wants sans serif")
        not Answer(subject == $subj)
        Answer(subject == "loves Garamond", answer == "no")
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask about user opinion of Eric Gill"
    agenda-group "book"
    salience 44
    when
        $q : Question($subj : subject == "opinion of Eric Gill")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user likes humanistic forms"
    agenda-group "book"
    salience 43
    when
        $q : Question($subj : subject == "likes humanistic forms")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask what cheese user preferes"
    agenda-group "book"
    salience 42
    when
        $q : Question($subj : subject == "preferred cheese")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user likes something condensed"
    agenda-group "infographic"
    salience 49
    when
        $q : Question($subj : subject == "likes condensed")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user got a lot of tables"
    agenda-group "infographic"
    salience 48
    when
        $q : Question($subj : subject == "got a lot of tables")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user cried watching Terminator"
    agenda-group "infographic"
    salience 47
    when
        $q : Question($subj : subject == "cried watching Terminator")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask where user is going to use typerface"
    agenda-group "newspaper"
    salience 49
    when
        $q : Question($subj : subject == "where in newspaper")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user is called boring"
    agenda-group "newspaper"
    salience 48
    when
        $q : Question($subj : subject == "is called boring")
        not Answer(subject == $subj)
        Answer(subject == "where in newspaper", answer == "text face")
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user wants something heavily used"
    agenda-group "newspaper"
    salience 47
    when
        $q : Question($subj : subject == "heavily used")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user wants something award winning"
    agenda-group "newspaper"
    salience 46
    when
        $q : Question($subj : subject == "award winning")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if Mr. Spiekermann is mostly right"
    agenda-group "newspaper"
    salience 48
    when
        $q : Question($subj : subject == "thinks Spiekermann is right")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if Netherlands is nice"
    agenda-group "newspaper"
    salience 47
    when
        $q : Question($subj : subject == "Netherlands is nice")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user likes it traditional"
    agenda-group "newspaper"
    salience 48
    when
        $q : Question($subj : subject == "likes it traditional")
        not Answer(subject == $subj)
        Answer(subject == "where in newspaper", answer == "display")
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if swiss is okay"
    agenda-group "newspaper"
    salience 47
    when
        $q : Question($subj : subject == "ok with swiss")
        not Answer(subject == $subj)
        Answer(subject == "likes traditional", answer == "yes")
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask about preferred age"
    agenda-group "newpaper"
    salience 46
    when
        $q : Question($subj : subject == "preferred age")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user wants something modern, yet planspoken"
    agenda-group "newspaper"
    salience 47
    when
        $q : Question($subj : subject == "moder yet plainspoken")
        not Answer(subject == $subj)
        Answer(subject == "likes it traditional", answer == "no")
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "ask if user pretends to live in nineties"
    agenda-group "newspaper"
    salience 46
    when
        $q : Question($subj : subject == "pretend to live in nineties")
        not Answer(subject == $subj)
        not Font()
    then
        String ans = askQuestion($q);
        insert(new Answer($q.subject, ans));
end

rule "when to choose Syntax"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "no")
//       Answer(subject == "sans serif", answer == "no")
//       Answer(subject == "opinion of Eric Gill", answer == "bad")
//       Answer(subject == "likes humanistic forms", answer == "yes")
       Answer(subject == "preffered cheese", answer == "emmental")
       not Font()
    then
       System.out.println("Best typeface for you is Syntax");
       insert(new Font("Syntax"));
end

rule "when to choose FF Scala"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "no")
//       Answer(subject == "sans serif", answer == "no")
//       Answer(subject == "opinion of Eric Gill", answer == "bad")
//       Answer(subject == "likes humanistic forms", answer == "yes")
       Answer(subject == "preffered cheese", answer == "gouda")
       not Font()
    then
       System.out.println("Best typeface for you is FF Scala");
       insert(new Font("FF Scala"));
end

rule "when to choose Baskerville"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "no")
//       Answer(subject == "sans serif", answer == "no")
//       Answer(subject == "opinion of Eric Gill", answer == "bad")
       Answer(subject == "likes humanistic forms", answer == "no")
       not Font()
    then
       System.out.println("Best typeface for you is Baskerville");
       insert(new Font("Baskerville"));
end

rule "when to choose Joanna"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "no")
//       Answer(subject == "sans serif", answer == "no")
       Answer(subject == "opinion of Eric Gill", answer == "good")
       not Font()
    then
       System.out.println("Best typeface for you is Joanna");
       insert(new Font("Joanna"));
end

rule "when to choose Optima"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "yes")
       Answer(subject == "would want a larger eye", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Optima");
       insert(new Font("Optima"));
end

rule "when to choose Sabon"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "yes")
       Answer(subject == "would want a larger eye", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Sabon");
       insert(new Font("Sabon"));
end

rule "when to choose Garamond"
    when
//       Answer(subject == "in doubt", answer == "no")
//       Answer(subject == "champion in usablity", answer == "no")
//       Answer(subject == "loves Garamond", answer == "yes")
       Answer(subject == "would want a larger eye", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Garamond");
       insert(new Font("Garamond"));
end

rule "when to choose Minion"
    when
//       Answer(subject == "in doubt", answer == "no")
       Answer(subject == "champion in usablity", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Minion");
       insert(new Font("Minion"));
end

rule "when to choose Caslon"
    when
       Answer(subject == "in doubt", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Caslon");
       insert(new Font("Caslon"));
end

rule "when to choose FF DIN"
    when
//       Answer(subject == "likes condensed", answer == "no")
//       Answer(subject == "got a lot of tables", answer == "no")
       Answer(subject == "cried watching Terminator", answer == "no")
       not Font()
    then
       System.out.println("Best typeface for you is FF Din");
       insert(new Font("FF DIN"));
end

rule "when to choose OCR"
    when
//       Answer(subject == "likes condensed", answer == "no")
//       Answer(subject == "got a lot of tables", answer == "no")
       Answer(subject == "cried watching Terminator", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is OCR");
       insert(new Font("OCR"));
end

rule "when to choose Letter Gothic"
    when
//       Answer(subject == "likes condensed", answer == "no")
       Answer(subject == "got a lot of tables", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Letter Gothic");
       insert(new Font("Letter Gothic"));
end

rule "when to choose Univers"
    when
       Answer(subject == "likes condensed", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Univers");
       insert(new Font("Univers"));
end

rule "when to choose Proforma"
    when
//       Answer(subject == "where in newspaper", answer == "text face")
//       Answer(subject == "user is called boring", answer == "no")
//       Answer(subject == "heavily used", answer == "no")
       Answer(subject == "award winning", answer == "good")
       not Font()
    then
       System.out.println("Best typeface for you is Proforma");
       insert(new Font("Proforma"));
end

rule "when to choose Miller"
    when
//       Answer(subject == "where in newspaper", answer == "text face")
//       Answer(subject == "user is called boring", answer == "no")
       Answer(subject == "heavily used", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Miller");
       insert(new Font("Miller"));
end

rule "when to choose Times"
    when
//       Answer(subject == "where in newspaper", answer == "text face")
       Answer(subject == "user is called boring", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Times");
       insert(new Font("Times"));
end

rule "when to choose Swift"
    when
       Answer(subject == "where in newspaper", answer == "combination")
       Answer(subject == "thinks Spiekermann is right", answer == "no")
       Answer(subject == "Netherlands is nice", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Swift");
       insert(new Font("Swift"));
end

rule "when to choose Arnhem"
    when
    (and
//       Answer(subject == "where in newspaper", answer == "text face")
//       Answer(subject == "user is called boring", answer == "no")
//       Answer(subject == "heavily used", answer == "no")
       Answer(subject == "award winning", answer == "bad")
    )
    or
    (and
//       Answer(subject == "where in newspaper", answer == "combination")
       Answer(subject == "thinks Spiekermann is right", answer == "yes")
    )
    not Font()
    then
       System.out.println("Best typeface for you is Arnhem");
       insert(new Font("Arnhem"));
end

rule "when to choose Interstate"
    when
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "yes")
//       Answer(subject == "ok with swiss", answer == "no")
       Answer(subject == "prefered age", answer == "new")
       not Font()
    then
       System.out.println("Best typeface for you is Interstate");
       insert(new Font("Interstate"));
end

rule "when to choose Helvetica"
    when
   (and
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "yes")
       Answer(subject == "ok with swiss", answer == "yes")
   )
    or
   (and
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "no")
//       Answer(subject == "modern yet plainspoken", answer == "no")
       Answer(subject == "pretend to live in the nineties", answer == "yes")
   )
       not Font()
    then
       System.out.println("Best typeface for you is Helvetica");
       insert(new Font("Helvetica"));
end

rule "when to choose FF Meta"
    when
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "no")
//       Answer(subject == "modern yet plainspoken", answer == "no")
       Answer(subject == "pretend to live in the nineties", answer == "no")
       not Font()
    then
       System.out.println("Best typeface for you is FF Meta");
       insert(new Font("FF Meta"));
end

rule "when to choose Gotham"
    when
//       Answer(subject == "where in newspaper", answer == "display")
//       Answer(subject == "likes it traditional", answer == "no")
       Answer(subject == "modern yet plainspoken", answer == "yes")
       not Font()
    then
       System.out.println("Best typeface for you is Gotham");
       insert(new Font("Gotham"));
end
